### ISSUE TITLE
onBuild input not published to NPM

### ISSUE THREAD

**Issue by turijs** [bencao/netlify-plugin-inline-functions-env#12]
Hey there,

First I wanted to say that this plugin really helped me out, so thanks!

I was getting build errors trying to use the plugin with the below configuration from the docs:
```toml
[[plugins]]
package = "netlify-plugin-inline-functions-env"
  [plugins.inputs]
  buildEvent = "onBuild"
```
I realized the NPM package isn't up to date with this repository, and ended up configuring my `package.json` to refer directly to the repo, after which the plugin worked great.

Is there any reason the latest version isn't published to NPM?
